baseURL = "https://medist.org"
languageCode = "en"
defaultContentLanguage = "en"
title = "medist.org | medical checklists"
theme = "tailwind-theme"
author = "Christian J."
enableGitInfo = true
mainSections = ['checklists', 'calculators']
googleAnalytics = 'G-R39L27N49K'

[languages]
  [languages.en]
    languageCode = "en"
    title = "medist.org"
    languageName = "English"
    weight = 1

  [languages.de]
    languageCode = "de"
    title = "medist.org"
    languageName = "German"
    weight = 2

[build]
writeStats = true

[frontmatter]
date = ['date', 'publishDate', 'lastmod']
expiryDate = ['expiryDate']
lastmod = [':git', 'lastmod', 'date', 'publishDate']
publishDate = ['publishDate', 'date']