baseURL = "https://medist.org"
languageCode = "en"
defaultContentLanguage = "en"
title = "medist.org | medical checklists"
theme = "tailwind-theme"
author = "Christian J."
enableGitInfo = true
mainSections = ['checklists', 'calculators']
googleAnalytics = 'G-R39L27N49K'

[languages]
  [languages.en]
    languageCode = "en"
    title = "medist.org"
    languageName = "English"
    weight = 1
    [languages.en.params]
    searchUrl = "search.json"

  [languages.de]
    languageCode = "de"
    title = "medist.org"
    languageName = "German"
    weight = 2
    [languages.de.params]
    searchUrl = "de/search.json"

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "search"

[outputs]
home = ['HTML', 'SearchIndex']
page = ['HTML']

[build]
writeStats = true

[frontmatter]
date = ['date', 'publishDate', 'lastmod']
expiryDate = ['expiryDate']
lastmod = [':git', 'lastmod', 'date', 'publishDate']
publishDate = ['publishDate', 'date']